# Generated by Django 3.0.6 on 2020-05-12 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='BOOK ID')),
                ('book_name', models.TextField(verbose_name='BOOK NAME')),
                ('book_category', models.CharField(max_length=100, verbose_name='BOOK CATEGORY')),
                ('book_description', models.TextField(verbose_name='BOOK DESCRIPTION')),
                ('book_author_name', models.CharField(max_length=256, verbose_name='AUTHOR Name')),
                ('book_price_to_sell', models.FloatField(verbose_name='Selling Price')),
                ('book_status', models.BooleanField(default=False, verbose_name='AVAILABILITY')),
                ('book_image', models.ImageField(upload_to='', verbose_name='IMAGE URL')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USERNAME')),
            ],
        ),
        migrations.CreateModel(
            name='Books_purchased',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Book')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserSold', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='UserPurchased', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
